travis:
  secure:
    BINSTAR_TOKEN: GU8SyICXW2Dg/SU4bBM4ldl6iIaISUu1SEoDMhA8/QLNB9oIT4H5Ns6Vtp3TBbSdEVsB7VnCBd69DPek1Q5fi8HGFg/GYFjLC3kwSny7f1WEB6N7yy5sLlR6PE5uWg/mxfzknmgo8jdsQv4kjQQx9BdDWHTIQPCl2nPwZIWLmzOAYwJI/Z95ydtqH7Gt8J6dkrX+WT83C/lvxCjb5SIm7ANqT+jbPLjNBMwGXMIwEonwqOHkyMxT0PsmM4onK249MAgo62ewXGPMZCyXHr8O+RavpgiTMTuLxfDwlI01CmpS9ttWxqEFUQiJh6QWox80/XWNqkk/PWVLbr9zqX1FhF+WC/fSBLYG0MwJrJHsbDmPW5FUNlyr4tEH4Klt0if7i2fD46jgYO5uo7JY08TolIpm4m7eHmsFG2iGKODrAd928JuF5f/1hZ8esaHoXCuNU/JKC5i1nJbrtNbXVOk65wkVZVoX/Xm7h1W3fjIFXyzkwI68gs03H6biHJ7aitZnCquXehU0qzU16/pnBIpl1MUE/4FGP/aEzHGSSgo29muV1X6djWu+aRsXUEJkP8SiPAei+w5260N4Y0u7aEAQ28W8K3JcrbyDfVyqWd0UL9ulhYYLegx138Ov9ol1eDeK3laMr83bI8bgLjXrbRnFJ3EPSTVY9j+GwQDYHtpo+ZU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
